<a href="https://colab.research.google.com/github/chi-hun/kaggle/blob/main/Bag_of_Words_Meets_Bags_of_Popcorn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bag of Words Meets Bags of Popcorn https://www.kaggle.com/competitions/word2vec-nlp-tutorial/overview

In [ ]:
!pip install konlpy

In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -r

In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
nltk.download("book", quiet=True)
from nltk.book import *
import tensorflow as tf

*** Introductory Examples for the NLTK Book ***
Loading text1, ..., text9 and sent1, ..., sent9
Type the name of the text or sentence to view it.
Type: 'texts()' or 'sents()' to list the materials.
text1: Moby Dick by Herman Melville 1851
text2: Sense and Sensibility by Jane Austen 1811
text3: The Book of Genesis
text4: Inaugural Address Corpus
text5: Chat Corpus
text6: Monty Python and the Holy Grail
text7: Wall Street Journal
text8: Personals Corpus
text9: The Man Who Was Thursday by G . K . Chesterton 1908


In [ ]:
from collections import Counter

In [ ]:
from konlpy.tag import Okt
with open('/content/대한민국헌법.txt', 'r', encoding='utf-8') as f:
    text = f.read()
text

'\ufeff대한민국헌법\n[시행 1988. 2. 25] [헌법 제10호, 1987. 10. 29, 전부개정]\n\n유구한 역사와 전통에 빛나는 우리 대한국민은 3·1운동으로 건립된 대한민국임시정부의 법통과 불의에 항거한 4·19민주이념을 계승하고, 조국의 민주개혁과 평화적 통일의 사명에 입각하여 정의·인도와 동포애로써 민족의 단결을 공고히 하고, 모든 사회적 폐습과 불의를 타파하며, 자율과 조화를 바탕으로 자유민주적 기본질서를 더욱 확고히 하여 정치·경제·사회·문화의 모든 영역에 있어서 각인의 기회를 균등히 하고, 능력을 최고도로 발휘하게 하며, 자유와 권리에 따르는 책임과 의무를 완수하게 하여, 안으로는 국민생활의 균등한 향상을 기하고 밖으로는 항구적인 세계평화와 인류공영에 이바지함으로써 우리들과 우리들의 자손의 안전과 자유와 행복을 영원히 확보할 것을 다짐하면서 1948년 7월 12일에 제정되고 8차에 걸쳐 개정된 헌법을 이제 국회의 의결을 거쳐 국민투표에 의하여 개정한다. \n       제1장 총강 \n제1조 ①대한민국은 민주공화국이다.\n  ②대한민국의 주권은 국민에게 있고, 모든 권력은 국민으로부터 나온다.\n제2조 ①대한민국의 국민이 되는 요건은 법률로 정한다.\n  ②국가는 법률이 정하는 바에 의하여 재외국민을 보호할 의무를 진다.\n제3조 대한민국의 영토는 한반도와 그 부속도서로 한다.\n제4조 대한민국은 통일을 지향하며, 자유민주적 기본질서에 입각한 평화적 통일 정책을 수립하고 이를 추진한다.\n제5조 ①대한민국은 국제평화의 유지에 노력하고 침략적 전쟁을 부인한다.\n  ②국군은 국가의 안전보장과 국토방위의 신성한 의무를 수행함을 사명으로 하며, 그 정치적 중립성은 준수된다.\n제6조 ①헌법에 의하여 체결·공포된 조약과 일반적으로 승인된 국제법규는 국내법과 같은 효력을 가진다.\n  ②외국인은 국제법과 조약이 정하는 바에 의하여 그 지위가 보장된다.\n제7조 ①공무원은 국민전체에 대한 봉사자이며, 국민에 대하여 책임을 진다.\n  ②공무원의

In [ ]:
okt = Okt()
text_o = okt.nouns(text)
text_o = [i for i in text_o if len(i) > 1]
text_c = Counter(text_o)

In [ ]:
text_c

In [ ]:
from wordcloud import WordCloud

In [ ]:
wc = WordCloud(font_path='NanumBarunGothic',width=400, height=400, scale=2.0, max_font_size=250,colormap='Reds')
gen = wc.generate_from_frequencies(text_c)
plt.figure()
plt.imshow(gen)
plt.colorbar()
plt.show()

# module

In [123]:
import pandas as pd
import re
from bs4 import BeautifulSoup
import nltk
import tensorflow as tf
from tensorflow.keras import layers
import sklearn
from gensim.models import word2vec
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

# data load

In [2]:
!pip install kaggle
from google.colab import files
files.upload()
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod -600 ~/.kaggle/kaggle.json

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


Saving kaggle.json to kaggle.json


In [3]:
!kaggle competitions download -c word2vec-nlp-tutorial

 95% 49.0M/51.7M [00:00<00:00, 71.2MB/s]
100% 51.7M/51.7M [00:00<00:00, 71.8MB/s]


In [4]:
!unzip /content/word2vec-nlp-tutorial.zip

Archive:  /content/word2vec-nlp-tutorial.zip
  inflating: labeledTrainData.tsv.zip  
  inflating: sampleSubmission.csv    
  inflating: testData.tsv.zip        
  inflating: unlabeledTrainData.tsv.zip  


In [5]:
!unzip /content/labeledTrainData.tsv.zip

Archive:  /content/labeledTrainData.tsv.zip
  inflating: labeledTrainData.tsv    


In [64]:
train = pd.read_csv('/content/labeledTrainData.tsv', delimiter='\t')
train.head(4)

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...
2  7759_3          0  The film starts with a manager (Nicholas Bell)...
3  3630_4          0  It must be assumed that those who praised this...

# 1. EDA

##  1, nltk + tensorflow



알파벳 숫자 제외 제거

In [65]:
train1 = train.copy()
def sp_out(x):
    x = BeautifulSoup(x, 'html.parser').get_text()
    x = re.sub('\W', ' ', x)
    return x
train1['review'] = train1['review'].apply(sp_out)
train1.head(4)

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1   The Classic War of the Worlds   by Timothy Hi...
2  7759_3          0  The film starts with a manager  Nicholas Bell ...
3  3630_4          0  It must be assumed that those who praised this...

불용어 제외한 단어로 토큰화

In [37]:
nltk.download('stopwords')
nltk.download('punkt')
def stopwords_token(x):
    stop_words = set(nltk.corpus.stopwords.words('english'))
    word = nltk.tokenize.word_tokenize(x.lower())
    word = [i for i in word if i not in stop_words]
    return word

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [66]:
train1['word'] = train1['review'].apply(stopwords_token)
train1.head(4)

id  sentiment                                             review  \
0  5814_8          1  With all this stuff going down at the moment w...   
1  2381_9          1   The Classic War of the Worlds   by Timothy Hi...   
2  7759_3          0  The film starts with a manager  Nicholas Bell ...   
3  3630_4          0  It must be assumed that those who praised this...   

                                                word  
0  [stuff, going, moment, mj, started, listening,...  
1  [classic, war, worlds, timothy, hines, enterta...  
2  [film, starts, manager, nicholas, bell, giving...  
3  [must, assumed, praised, film, greatest, filme...

텐서플로우 이용 백터(라벨)화

In [70]:
tf_token = tf.keras.preprocessing.text.Tokenizer()
tf_token.fit_on_texts(train1['word'])
train1['label'] = tf_token.texts_to_sequences(train1['word'])
train1.head(5)

id  sentiment                                             review  \
0  5814_8          1  With all this stuff going down at the moment w...   
1  2381_9          1   The Classic War of the Worlds   by Timothy Hi...   
2  7759_3          0  The film starts with a manager  Nicholas Bell ...   
3  3630_4          0  It must be assumed that those who praised this...   
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...   

                                                word  \
0  [stuff, going, moment, mj, started, listening,...   
1  [classic, war, worlds, timothy, hines, enterta...   
2  [film, starts, manager, nicholas, bell, giving...   
3  [must, assumed, praised, film, greatest, filme...   
4  [superbly, trashy, wondrously, unpretentious, ...   

                                               label  
0  [410, 71, 425, 8956, 511, 2484, 116, 54, 881, ...  
1  [236, 207, 3086, 3611, 7239, 321, 2, 411, 155,...  
2  [2, 388, 2854, 4457, 3780, 604, 2210, 18035, 5...  
3  [101, 4896, 5399, 2, 688, 670, 1272, 42, 215, ...  
4  [3409, 4193, 37747, 11135, 859, 2062, 13202, 1...

제로패딩(post 뒤쪽이 0)

In [68]:
token_index = tf_token.word_index
token_index['<PAD>'] = 0
len(token_index)

75789

In [69]:
print(train1['label'].str.len().min())
print(train1['label'].str.len().quantile(0.75))
print(train1['label'].str.len().max())

4
148.0
1429


In [72]:
max_padding = 214
x_train1 = tf.keras.preprocessing.sequence.pad_sequences(train1['label'], maxlen=max_padding, padding='post')
y_train1 = train1['sentiment']

In [74]:
x_train1

array([[  116,    54,   881, ..., 18947,   320,  1372],
       [  236,   207,  3086, ...,     0,     0,     0],
       [ 4657, 32515,  3589, ...,   707,  1187,  5398],
       ...,
       [  118,  3144,    14, ...,     0,     0,     0],
       [  831,   644,   521, ...,     0,     0,     0],
       [  110,     1,   354, ...,     0,     0,     0]], dtype=int32)

In [78]:
x_train1.shape

(25000, 214)

## 2, sklearn(countervector, TfidfVectorizer)

sklearn(countervector)

In [84]:
train2 = train.copy()
ctv = sklearn.feature_extraction.text.CountVectorizer(analyzer = "word", max_features = 5000,ngram_range=(1,3))
x_train2 = ctv.fit_transform(list(train2['review']))
print(x_train2.shape)
print(x_train2.toarray())

(25000, 5000)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


sklearn(TfidfVectorizer)

In [107]:
train3 = train.copy()
tfv = sklearn.feature_extraction.text.TfidfVectorizer(min_df=0.0, analyzer = "word", sublinear_tf=True,
                           ngram_range=(1,3), max_features=1000,stop_words = 'english')

# min_df : 설정값보다 특정 토큰의 df(document Frequency)가 적으면 벡터화에서 제거
# analyzer : word/char 2가지 : word는 단위 : 단어 / char : 단위 : char 
# sublinear_tf : term frequency에 대한 smoothing 여부
# ngram_range = n-gram 의 범위 : 분석기에 의해 설정값을 사용하여 ngram자동 생성
# max_features = 벡터의 최대 길이
train3 = tfv.fit_transform(list(train3['review']))
print(train3.shape)
print(train3.toarray())

(25000, 1000)
[[0.         0.         0.10291081 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.07911234 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.13631309 0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


## 3, word2vec

In [109]:
x_train4 = []
for i in list(train['review']):
    x_train4.append(i.split())
len(x_train4)

25000

In [89]:
# 하이퍼파라미터
num_features = 1000 # word2vec 특징 수
min_word_count =20 
num_workers = 6
context =10 # Word2vec 수행을 위한 컨텍스트 윈도 크기
# https://medium.com/@omicro03/%EC%9E%90%EC%97%B0%EC%96%B4%EC%B2%98%EB%A6%AC-nlp-13%EC%9D%BC%EC%B0%A8-word2vec-3c82ec870426
downsampling = 1e-3 #Word2vec 빠른 학습을 위해 정답 단어 라벨에 대한 다운 샘플링, 보통 0.001이 좋은 성능
#Downsampling of frequent words # 자주 나오는 단어에 대해서는 0.001 만큼 다운 샘플링하여 시간을 아낌

In [99]:
model = word2vec.Word2Vec(x_train4,
                          workers = num_workers,
                          size = num_features,
                          min_count = min_word_count,
                          window =  context,
                          sample = downsampling,
                          iter = 10,
                          sg =0 # sg =0 CBOW, 1 : skip-gram
                         )

In [103]:
model.wv.most_similar('boy')

[('boy,', 0.7409906983375549),
 ('girl', 0.7325389385223389),
 ('kid', 0.6940426826477051),
 ('son', 0.6774898767471313),
 ('girl,', 0.6488686800003052),
 ('priest', 0.646533191204071),
 ('girl.', 0.6331642866134644),
 ('man', 0.6205923557281494),
 ('lady', 0.6176725625991821),
 ('baby', 0.6156284213066101)]

In [110]:
# word2vec 은 단어 하나하나가 벡터로 표현되어 있다.
# Review 데이터는 단어들의 조합이기에 Review를 벡터로 표현하기 위해
# Review에 포함된 단어 벡터들의 평균값을 만든다.
# 다른 방법으로는 Doc2vec, average of word2vec vectors with TF-IDF
# Just take the word vectors and multiply it with their TF-IDF scores. Just take the average and it will represent your sentence vector.
 # 단어 벡터에 TF-IDF를 곱해서 평균 내는 방법
    
# https://stackoverflow.com/questions/29760935/how-to-get-vector-for-a-sentence-from-the-word2vec-of-tokens-in-sentence

def get_features(words, model, num_features):
    feature_vector = np.zeros((num_features), dtype = np.float32)
    
    num_words = 0
    # 어휘 사전
    index2word_set = set(model.wv.index2word)
    
    for w in words:
        if w in index2word_set:
            num_words +=1
            #사전에 해당하는 단어에 대해 단어 벡터를 더함
            
            feature_vector = np.add(feature_vector, model[w])
            # model은 단어들에 대한 vector를 다 가지고 있음
            # num_features 만큼 이미 학습할때 정의해서 만들어놓음 
            
    feature_vector = np.divide(feature_vector,num_words)
    
    return feature_vector

def get_dataset(reviews, model, num_features):
    dataset = list()

    
    for s in reviews :
        dataset.append(get_features(s,model,num_features))
    
    reviewFeaturevecs = np.stack(dataset)
    
    return reviewFeaturevecs

x_train4 = get_dataset(x_train4,model,num_features)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).


In [106]:
x_train4.shape

(25000, 1000)

# modeling

## 1, randomforest(x_train1~4) 

In [112]:
rfc = RandomForestClassifier()
y_train = train['sentiment']

nltk(train1)

In [113]:
x_ttrain, x_ttest, y_ttrain, y_ttest = train_test_split(x_train1, y_train, stratify=y_train)
model = rfc.fit(x_ttrain, y_ttrain)
pre = model.predict(x_ttest)
sc = round(model.score(x_ttrain, y_ttrain), 4)
rasc = round(roc_auc_score(y_ttest, pre), 4)
print(f'sc : {sc}, rasc : {rasc}')

sc : 1.0, rasc : 0.545


countervector(train2)

In [115]:
x_ttrain, x_ttest, y_ttrain, y_ttest = train_test_split(x_train2, y_train, stratify=y_train)
model = rfc.fit(x_ttrain, y_ttrain)
pre = model.predict(x_ttest)
sc = round(model.score(x_ttrain, y_ttrain), 4)
rasc = round(roc_auc_score(y_ttest, pre), 4)
print(f'sc : {sc}, rasc : {rasc}')

sc : 1.0, rasc : 0.8424


TfidfVectorizer(train3)

In [116]:
x_ttrain, x_ttest, y_ttrain, y_ttest = train_test_split(x_train3, y_train, stratify=y_train)
model = rfc.fit(x_ttrain, y_ttrain)
pre = model.predict(x_ttest)
sc = round(model.score(x_ttrain, y_ttrain), 4)
rasc = round(roc_auc_score(y_ttest, pre), 4)
print(f'sc : {sc}, rasc : {rasc}')

sc : 1.0, rasc : 0.813


word2vec(train4)

In [117]:
x_ttrain, x_ttest, y_ttrain, y_ttest = train_test_split(x_train4, y_train, stratify=y_train)
model = rfc.fit(x_ttrain, y_ttrain)
pre = model.predict(x_ttest)
sc = round(model.score(x_ttrain, y_ttrain), 4)
rasc = round(roc_auc_score(y_ttest, pre), 4)
print(f'sc : {sc}, rasc : {rasc}')

sc : 1.0, rasc : 0.8074


## 2, tensorflow

### a, simple embedding

In [132]:
train_t = train.copy()
def sp_out(x):
    x = BeautifulSoup(x, 'html.parser').get_text()
    x = re.sub('\W', ' ', x)
    return x
train_t['review'] = train_t['review'].apply(sp_out)
train_t.head(4)

id  sentiment                                             review
0  5814_8          1  With all this stuff going down at the moment w...
1  2381_9          1   The Classic War of the Worlds   by Timothy Hi...
2  7759_3          0  The film starts with a manager  Nicholas Bell ...
3  3630_4          0  It must be assumed that those who praised this...

In [134]:
def token_stout(x):
    stop_words = set(nltk.corpus.stopwords.words('english'))
    x = nltk.tokenize.word_tokenize(x.lower())
    x = [i for i in x if i not in stop_words]
    return x
train_t['review'] = train_t['review'].apply(token_stout)
train_t.head(4)

id  sentiment                                             review
0  5814_8          1  [stuff, going, moment, mj, started, listening,...
1  2381_9          1  [classic, war, worlds, timothy, hines, enterta...
2  7759_3          0  [film, starts, manager, nicholas, bell, giving...
3  3630_4          0  [must, assumed, praised, film, greatest, filme...

In [147]:
Tokenizer = tf.keras.preprocessing.text.Tokenizer()
Tokenizer.fit_on_texts(train_t['review'])
train_t['review'] = Tokenizer.texts_to_sequences(train_t['review'])
train_t['review'].shape

(25000,)

In [154]:
word_index = Tokenizer.word_index
word_index['<PAD>'] = 0
input_dim = len(word_index) +1
input_dim

75790

In [150]:
print(train_t['review'].str.len().quantile(0.75))
print(train_t['review'].str.len().quantile(0.90))
print(train_t['review'].str.len().max())

148.0
240.0
1429


In [152]:
maxlen = 240
x_train_t = tf.keras.preprocessing.sequence.pad_sequences(train_t['review'], maxlen=maxlen, padding='post')
y_train_t = train_t['sentiment']
x_train_t.shape, y_train_t.shape

((25000, 240), (25000,))

In [163]:
def model_make1():
    inputs = layers.Input(shape=(240))
    x = layers.Embedding(input_dim=input_dim, output_dim=128, input_length=maxlen)(inputs)
    x = layers.LSTM(128, return_sequences=True)(x)
    x = layers.LSTM(128)(x)
    x = layers.Dense(128, activation='tanh')(x)
    x = layers.Dense(64, activation='tanh')(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)

    model = tf.keras.Model(inputs, outputs)
    return model

In [164]:
model = model_make1()
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 240)]             0         
                                                                 
 embedding_2 (Embedding)     (None, 240, 128)          9701120   
                                                                 
 lstm_2 (LSTM)               (None, 240, 128)          131584    
                                                                 
 lstm_3 (LSTM)               (None, 128)               131584    
                                                                 
 dense (Dense)               (None, 128)               16512     
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65    

In [165]:
model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(), metrics=['accuracy'])

In [166]:
his = model.fit(x_train_t, y_train_t, epochs=10, validation_split=0.2)

Epoch 1/10
625/625 [==============================] - 481s 746ms/step - loss: 0.6933 - accuracy: 0.5173 - val_loss: 0.6787 - val_accuracy: 0.5668
Epoch 2/10
389/625 [=================>............] - ETA: 2:34 - loss: 0.6802 - accuracy: 0.5567

KeyboardInterrupt: ignored